name: Install PostgresSQL Database
on: workflow_dispatch

jobs:
  install-pg:
    runs-on: [ubuntu-latest]
    steps:
      - uses: minesunny/postgresql-action@v1.0.0
        with:
          postgresql version: '11'
     
