name: Setup Local PostgresSQL Database
on: workflow_dispatch

jobs:
  setup-pg-local:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: minesunny/postgresql-action@v1.0.0
        with:
          postgresql version: '11'
     
